/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategyComparisonRouteImport } from './routes/strategy-comparison'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModelInsightsRouteImport } from './routes/model-insights'
import { Route as LearningEvolutionRouteImport } from './routes/learning-evolution'
import { Route as ExperimentSetupRouteImport } from './routes/experiment-setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnotationLabRouteImport } from './routes/annotation-lab'
import { Route as IndexRouteImport } from './routes/index'

const StrategyComparisonRoute = StrategyComparisonRouteImport.update({
  id: '/strategy-comparison',
  path: '/strategy-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelInsightsRoute = ModelInsightsRouteImport.update({
  id: '/model-insights',
  path: '/model-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningEvolutionRoute = LearningEvolutionRouteImport.update({
  id: '/learning-evolution',
  path: '/learning-evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentSetupRoute = ExperimentSetupRouteImport.update({
  id: '/experiment-setup',
  path: '/experiment-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotationLabRoute = AnnotationLabRouteImport.update({
  id: '/annotation-lab',
  path: '/annotation-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annotation-lab': typeof AnnotationLabRoute
  '/auth': typeof AuthRoute
  '/experiment-setup': typeof ExperimentSetupRoute
  '/learning-evolution': typeof LearningEvolutionRoute
  '/model-insights': typeof ModelInsightsRoute
  '/settings': typeof SettingsRoute
  '/strategy-comparison': typeof StrategyComparisonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annotation-lab': typeof AnnotationLabRoute
  '/auth': typeof AuthRoute
  '/experiment-setup': typeof ExperimentSetupRoute
  '/learning-evolution': typeof LearningEvolutionRoute
  '/model-insights': typeof ModelInsightsRoute
  '/settings': typeof SettingsRoute
  '/strategy-comparison': typeof StrategyComparisonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annotation-lab': typeof AnnotationLabRoute
  '/auth': typeof AuthRoute
  '/experiment-setup': typeof ExperimentSetupRoute
  '/learning-evolution': typeof LearningEvolutionRoute
  '/model-insights': typeof ModelInsightsRoute
  '/settings': typeof SettingsRoute
  '/strategy-comparison': typeof StrategyComparisonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annotation-lab'
    | '/auth'
    | '/experiment-setup'
    | '/learning-evolution'
    | '/model-insights'
    | '/settings'
    | '/strategy-comparison'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annotation-lab'
    | '/auth'
    | '/experiment-setup'
    | '/learning-evolution'
    | '/model-insights'
    | '/settings'
    | '/strategy-comparison'
  id:
    | '__root__'
    | '/'
    | '/annotation-lab'
    | '/auth'
    | '/experiment-setup'
    | '/learning-evolution'
    | '/model-insights'
    | '/settings'
    | '/strategy-comparison'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnotationLabRoute: typeof AnnotationLabRoute
  AuthRoute: typeof AuthRoute
  ExperimentSetupRoute: typeof ExperimentSetupRoute
  LearningEvolutionRoute: typeof LearningEvolutionRoute
  ModelInsightsRoute: typeof ModelInsightsRoute
  SettingsRoute: typeof SettingsRoute
  StrategyComparisonRoute: typeof StrategyComparisonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategy-comparison': {
      id: '/strategy-comparison'
      path: '/strategy-comparison'
      fullPath: '/strategy-comparison'
      preLoaderRoute: typeof StrategyComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-insights': {
      id: '/model-insights'
      path: '/model-insights'
      fullPath: '/model-insights'
      preLoaderRoute: typeof ModelInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-evolution': {
      id: '/learning-evolution'
      path: '/learning-evolution'
      fullPath: '/learning-evolution'
      preLoaderRoute: typeof LearningEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiment-setup': {
      id: '/experiment-setup'
      path: '/experiment-setup'
      fullPath: '/experiment-setup'
      preLoaderRoute: typeof ExperimentSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotation-lab': {
      id: '/annotation-lab'
      path: '/annotation-lab'
      fullPath: '/annotation-lab'
      preLoaderRoute: typeof AnnotationLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnotationLabRoute: AnnotationLabRoute,
  AuthRoute: AuthRoute,
  ExperimentSetupRoute: ExperimentSetupRoute,
  LearningEvolutionRoute: LearningEvolutionRoute,
  ModelInsightsRoute: ModelInsightsRoute,
  SettingsRoute: SettingsRoute,
  StrategyComparisonRoute: StrategyComparisonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
